src/Entity/Campus.php
<?php

namespace App\Entity;

use App\Repository\CampusRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CampusRepository::class)
 */
class Campus
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $idCampus;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;


    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Sortie", mappedBy="campus")
     */
    private $listeSorties;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Participant", mappedBy="campus")
     */
    private $listeParticipants;

    public function __construct()
    {
        $this->listeParticipants = new ArrayCollection();
        $this->listeSorties = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->idCampus;
    }


    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getListeSorties(): ArrayCollection
    {
        return $this->listeSorties;
    }

    /**
     * @param ArrayCollection $listeSorties
     */
    public function setListeSorties(ArrayCollection $listeSorties): void
    {
        $this->listeSorties = $listeSorties;
    }

    /**
     * @return ArrayCollection
     */
    public function getListeParticipants(): ArrayCollection
    {
        return $this->listeParticipants;
    }

    /**
     * @param ArrayCollection $listeParticipants
     */
    public function setListeParticipants(ArrayCollection $listeParticipants): void
    {
        $this->listeParticipants = $listeParticipants;
    }

    public function __toString()
    {
        return $this->nom;
    }


}

src/Form/CampusType.php
<?php

namespace App\Form;

use App\Entity\Campus;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CampusType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Campus::class,
        ]);
    }
}

src/Controller/CampusController.php
<?php

namespace App\Controller;

use App\Entity\Campus;
use App\Form\CampusType;
use App\Repository\CampusRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/campus")
 */
class CampusController extends AbstractController
{
    /**
     * @Route("/", name="campus_index", methods={"GET"})
     */
    public function index(CampusRepository $campusRepository): Response
    {
        return $this->render('campus/index.html.twig', [
            'campus' => $campusRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="campus_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $campus = new Campus();
        $form = $this->createForm(CampusType::class, $campus);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($campus);
            $entityManager->flush();

            return $this->redirectToRoute('campus_index');
        }

        return $this->render('campus/new.html.twig', [
            'campus' => $campus,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{idCampus}", name="campus_show", methods={"GET"})
     */
    public function show(Campus $campus): Response
    {
        return $this->render('campus/show.html.twig', [
            'campu' => $campus,
        ]);
    }

    /**
     * @Route("/{idCampus}/edit", name="campus_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Campus $campus): Response
    {
        $form = $this->createForm(CampusType::class, $campus);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('campus_index');
        }

        return $this->render('campus/edit.html.twig', [
            'campus' => $campus,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{idCampus}", name="campus_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Campus $campus): Response
    {
        if ($this->isCsrfTokenValid('delete'.$campus->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($campus);
            $entityManager->flush();
        }

        return $this->redirectToRoute('campus_index');
    }
}

templates/campus/_delete_form.html.twig
<form method="post" action="{{ path('campus_delete', {'idCampus': campus.id}) }}" onsubmit="return confirm('Etes vous sûr de vouloir supprimer ce campus?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ campus.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/campus/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Enregister') }}</button>
{{ form_end(form) }}

templates/campus/edit.html.twig
{% extends 'layoutAdmin.html.twig' %}

{% block title %}Edit Campus{% endblock %}

{% block body %}
    <h1 class="text-center">Modifier les campus</h1>

    {{ include('campus/_form.html.twig', {'button_label': 'Editer'}) }}

    <a href="{{ path('campus_index') }}">Retour</a>

    {{ include('campus/_delete_form.html.twig') }}
{% endblock %}

templates/campus/index.html.twig
{% extends 'layoutAdmin.html.twig' %}

{% block title %}Campus index{% endblock %}

{% block body %}
    <br>
    <h1 class="text-center">Gérer les campus</h1>
    <br>
    <h3>Filtrer les campus</h3>
    <br>
    <tr class="label">Le nom contient : </tr> <input>    <button class="btn btn-success" type="submit">Rechercher</button>
    <br>
    <br>
    <br>
    <table class="table">
        <thead>
            <tr>

                <th >Nom</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for campus in campus %}
            <tr>

                <td>{{ campus.nom }}</td>

                <td>
                    <a href="{{ path('campus_edit', {'idCampus': campus.id}) }}">Modifier</a>
                    <a href="{{ path('campus_delete', {'idCampus': campus.id}) }}">Supprimer</a>

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('campus_new') }}">Ajouter</a>
{% endblock %}

templates/campus/new.html.twig
{% extends 'layoutAdmin.html.twig' %}
{% block title %}New Campus{% endblock %}

{% block body %}
    <h1 class="text-center">Ajouter un campus</h1>

    {{ include('campus/_form.html.twig') }}

    <a class="btn btn-primary" href="{{ path('campus_index') }}">Retour</a>
{% endblock %}

templates/campus/show.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Campus{% endblock %}

{% block body %}
    <h1>Campus</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>IdCampus</th>
                <td>{{ campus.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ campus.nom }}</td>
            </tr>
        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('campus_index') }}">Retour à la liste</a>

    <a class="btn btn-primary" href="{{ path('campus_edit', {'idCampus': campus.id}) }}">Editer</a>

    {{ include('campus/_delete_form.html.twig') }}
{% endblock %}